export const CHANGE_STATUS_SHOW_CART = "CHANGE_STATUS_SHOW_CART"
export const CHANGE_STATUS_SHOW_INFO_PRODUCT = "CHANGE_STATUS_SHOW_INFO_PRODUCT"
export const GET_ID_FOOD = "GET_ID_FOOD"
export const GET_ID_DRINK = "GET_ID_DRINK"
export const GET_KEY_SEARCH = "GET_KEY_SEARCH"
export const ADD_PRODUCT = "ADD_PRODUCT"


